### ISSUE TITLE
tap-paypal to SDK

### ISSUE THREAD

**Issue by prratek** [MeltanoLabs/Singer-Most-Wanted#20]
The existing options either support a [very limited](https://github.com/Yoast/singer-tap-paypal) set of streams or appear to be [inactive](https://github.com/milk-bar/tap-paypal).

**Comment by pnadolny13** [comment]
https://hub.meltano.com/extractors/tap-paypal--epoch8/ (SDK) and https://hub.meltano.com/extractors/tap-paypal--airbyte/ are new options that look to solve this case
