### ISSUE TITLE
tap-aws-costexplorer

### ISSUE THREAD

**Issue by andrewcstewart** [MeltanoLabs/Singer-Most-Wanted#26]

**Comment by albert-marrero** [comment]
I think I got something here. However, I dont know what they end results should be. https://github.com/albert-marrero/tap-awscostexplorer

**Comment by albert-marrero** [comment]
@tayloramurphy, Thank you for your updates and I would love to mimic what the MeltanoLabs repo. I have updated everything based on your suggestions.

If possible, I would like to keep it in my namespace.  If it needs to move to the MeltanoLabs so I can get that stein, I am ok with that.  Here is the new repo link: https://github.com/albert-marrero/tap-aws-cost-explorer.

**Comment by albert-marrero** [comment]
I thought this was done, why is it in the most wanted list :-(

**Comment by edgarrmondragon** [comment]
> I thought this was done, why is it in the most wanted list :-(

@albert-marrero this has been live [in Meltano Hub](https://hub.meltano.com/extractors/tap-aws-cost-explorer/) for a while, so this issue can probably be closed 🙂
