### ISSUE TITLE
tap-clickup

### ISSUE THREAD

**Issue by bjwise96** [MeltanoLabs/Singer-Most-Wanted#32]
https://clickup.com/api

**Comment by pnadolny13** [comment]
@bjwise96 @visch I looks like we can probably close out this issue if https://github.com/AutoIDM/tap-clickup is working for you all. Its on MeltanoHub as the default variant already!

**Comment by vischtest** [comment]
Yeah go ahead, and close this from my end!

**Comment by visch** [comment]
Sounds good to me!
