### ISSUE TITLE
tap kafka

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/Singer-Most-Wanted#64]

**Comment by crowemi** [comment]
@pnadolny13, duplicate of #61 ?

**Comment by pnadolny13** [comment]
@crowemi yep youre right, this was supposed to be _tap_ kafka. I updated the title!

**Comment by pnadolny13** [comment]
A bunch of variants already exist for this https://hub.meltano.com/extractors/tap-kafka so I'm updating it to be "to SDK".
